
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: backend-service
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - hsreporter-net
    env_file:
      - backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    container_name: frontend-service
    depends_on:
      - backend
    networks:
      - hsreporter-net
    env_file:
      - frontend/.env

networks:
  hsreporter-net:
    driver: bridge
